apiVersion: apps/v1
kind: Deployment
metadata:
   name: sketchbrain-backend-deploy
spec:
   replicas: 2
   selector:
      matchLabels:
         app: sketchbrain-backend
   template:
       metadata:
          labels:
             app: sketchbrain-backend
       spec:
          imagePullSecrets:
          - name: docker-pull-secret
          containers:
          - name: sketchbrain-backend
            image: hhlee7175/sketchbrain-backend:0.2
            ports:
            - name: backend-port
              containerPort: 8080
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
            resources:
              requests:
                cpu: "500m"
                memory: "1024Mi"
              limits:
                cpu: "500m"
                memory: "1024Mi"
          volumes:
          - name: tz-seoul
            hostPath:
                path: /usr/share/zoneinfo/Asia/Seoul
