apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
     name: sketchbrain-backend-hpa
spec:
    scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: sketchbrain-backend-deploy
    targetCPUUtilizationPercentage: 50
    maxReplicas: 5
    minReplicas: 2
