apiVersion: v1
kind: Service
metadata:
   name: sketchbrain-backend-svc
   labels:
       app: sketchbrain-backend
spec:
   type: ClusterIP
   ports:
   - name: backend-port
     port: 8080
     targetPort: 8080
   selector:
       app: sketchbrain-backend
