name: Run Test
on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: src/main/resources/application.properties
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ${{ env.CONFIG_FILE  }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Test With Gradle
        run: ./gradlew --info test